/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	scheme "github.com/kubeovn/kube-ovn/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VpcGatewaysGetter has a method to return a VpcGatewayInterface.
// A group's client should implement this interface.
type VpcGatewaysGetter interface {
	VpcGateways(namespace string) VpcGatewayInterface
}

// VpcGatewayInterface has methods to work with VpcGateway resources.
type VpcGatewayInterface interface {
	Create(ctx context.Context, vpcGateway *kubeovnv1.VpcGateway, opts metav1.CreateOptions) (*kubeovnv1.VpcGateway, error)
	Update(ctx context.Context, vpcGateway *kubeovnv1.VpcGateway, opts metav1.UpdateOptions) (*kubeovnv1.VpcGateway, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vpcGateway *kubeovnv1.VpcGateway, opts metav1.UpdateOptions) (*kubeovnv1.VpcGateway, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*kubeovnv1.VpcGateway, error)
	List(ctx context.Context, opts metav1.ListOptions) (*kubeovnv1.VpcGatewayList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *kubeovnv1.VpcGateway, err error)
	VpcGatewayExpansion
}

// vpcGateways implements VpcGatewayInterface
type vpcGateways struct {
	*gentype.ClientWithList[*kubeovnv1.VpcGateway, *kubeovnv1.VpcGatewayList]
}

// newVpcGateways returns a VpcGateways
func newVpcGateways(c *KubeovnV1Client, namespace string) *vpcGateways {
	return &vpcGateways{
		gentype.NewClientWithList[*kubeovnv1.VpcGateway, *kubeovnv1.VpcGatewayList](
			"vpc-gateways",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kubeovnv1.VpcGateway { return &kubeovnv1.VpcGateway{} },
			func() *kubeovnv1.VpcGatewayList { return &kubeovnv1.VpcGatewayList{} },
		),
	}
}
