/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VpcGatewayLister helps list VpcGateways.
// All objects returned here must be treated as read-only.
type VpcGatewayLister interface {
	// List lists all VpcGateways in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.VpcGateway, err error)
	// VpcGateways returns an object that can list and get VpcGateways.
	VpcGateways(namespace string) VpcGatewayNamespaceLister
	VpcGatewayListerExpansion
}

// vpcGatewayLister implements the VpcGatewayLister interface.
type vpcGatewayLister struct {
	listers.ResourceIndexer[*kubeovnv1.VpcGateway]
}

// NewVpcGatewayLister returns a new VpcGatewayLister.
func NewVpcGatewayLister(indexer cache.Indexer) VpcGatewayLister {
	return &vpcGatewayLister{listers.New[*kubeovnv1.VpcGateway](indexer, kubeovnv1.Resource("vpcgateway"))}
}

// VpcGateways returns an object that can list and get VpcGateways.
func (s *vpcGatewayLister) VpcGateways(namespace string) VpcGatewayNamespaceLister {
	return vpcGatewayNamespaceLister{listers.NewNamespaced[*kubeovnv1.VpcGateway](s.ResourceIndexer, namespace)}
}

// VpcGatewayNamespaceLister helps list and get VpcGateways.
// All objects returned here must be treated as read-only.
type VpcGatewayNamespaceLister interface {
	// List lists all VpcGateways in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.VpcGateway, err error)
	// Get retrieves the VpcGateway from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubeovnv1.VpcGateway, error)
	VpcGatewayNamespaceListerExpansion
}

// vpcGatewayNamespaceLister implements the VpcGatewayNamespaceLister
// interface.
type vpcGatewayNamespaceLister struct {
	listers.ResourceIndexer[*kubeovnv1.VpcGateway]
}
