apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: RequestResponse
    resources:
      - group: ""
        resources:
          - nodes
          - namespaces
          - pods
          - services
          - endpoints
    verbs:
      - patch
      - update
omitManagedFields: true
