name: Build Base
on: workflow_dispatch

jobs:
  build-amd64:
    name: Build AMD64
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: |
          make base-amd64
          make base-tar-amd64

      - name: Upload image to artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-amd64
          path: image-amd64.tar
