name: Build Base
on: workflow_dispatch

jobs:
  build-amd64:
    name: Build AMD64
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        run: |
          make base-amd64
          make base-tar-amd64

      - name: Upload image to artifact
        uses: actions/upload-artifact@v2
        with:
          name: image-amd64
          path: image-amd64.tar

  push:
    needs:
      - build-amd64
    name: push
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image-amd64

      - name: Load Image
        run: |
          docker load --input image-amd64.tar

      - name: Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMMIT: ${{ github.sha }}
        run: |
          cat VERSION
          TAG=$(cat VERSION)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker images
          docker push zhangzujian/kube-ovn-base:$TAG-amd64
          docker manifest create zhangzujian/kube-ovn-base:$TAG zhangzujian/kube-ovn-base:$TAG-amd64
          docker manifest push zhangzujian/kube-ovn-base:$TAG
