name: Build x86 Image

on:
  pull_request:
    branches:
    - master
    - release-*
    paths-ignore:
    - 'docs/**'
    - '**.md'
  push:
    branches:
    - master
    - release-*
    paths-ignore:
    - 'docs/**'
    - '**.md'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  GOSEC_VERSION: '2.15.0'
  HELM_VERSION: v3.11.1
  SUBMARINER_VERSION: '0.14.3'

jobs:
  lb-svc-e2e:
    name: LB Service E2E
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        index:
          - 0
          - 1
          - 2
          - 3
          - 4
    steps:
      - uses: actions/checkout@v3

      - run: sudo touch /continue 
      - uses: lhotari/action-upterm@v1

      - name: Create the default branch directory
        if: (github.base_ref || github.ref_name) != github.event.repository.default_branch
        run: mkdir -p test/e2e/source

      - name: Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true

      - name: Create kind cluster
        run: |
          sudo pip3 install j2cli
          sudo pip3 install "j2cli[yaml]"
          sudo PATH=~/.local/bin:$PATH make kind-init
          sudo cp -r /root/.kube/ ~/.kube/
          sudo chown -R $(id -un). ~/.kube/

      - name: Install Multus
        id: install
        run: make kind-install-multus

      - if: failure() && steps.install.outcome != 'success'
        run: sleep infinity
